class_name Item
extends Resource

@export_enum("Power Beam", 
"Ice Beam", 
"Wave Beam", 
"Plasma Beam",
"Combat Visor",
"Scan Visor",
"Thermal Visor",
"X-Ray Visor",
"Space Jump",
"Varia Suit",
"Gravity Suit",
"Phazon Suit",
"Morph Ball",
"Morph Ball Bombs",
"Boost Ball",
"Spider Ball",
"Power Bomb",
"Grapple Beam",
"Charge Beam",
"Super Missile",
"Wavebuster",
"Ice Spreader",
"Flamethrower",
"Artifact",
"Energy Tank",
"Missile") var item : String
